#! /usr/bin/python3
import argparse
import subprocess
parser = argparse.ArgumentParser()
parser.add_argument("key", help = 'identify whether it is for train or test')
parser.add_argument("file_name", help = "input file name")
parser.add_argument("input_json", help = "input json file name")
parser.add_argument("output_json", help = "output json file name")
args = parser.parse_args()
if args.key == 'train':
    import json
    with open(args.input_json,'r') as f:
        names = json.load(f)
    output_list = []
    for name in names:
        data = subprocess.check_output(['python3',args.file_name,name['name']])
        data = data.decode("utf-8")
        print(data)
        output_list.append(data) 
    with open(args.output_json,'w') as outfile:
        json.dump(output_list,outfile)
