"""empty message

Revision ID: 6088faf1ccd5
Revises: 1191949070a3
Create Date: 2018-09-13 16:51:34.085007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6088faf1ccd5'
down_revision = '1191949070a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    # ### end Alembic commands ###
